services: docker
git:
  depth: false
install: make docker-login build-docker
stages:
- name: publish-docker
jobs:
  include:
  - stage: publish
    name: Publish docker image
    script:
    - make docker-login publish-docker
env:
  global:
  - secure: P+JtbZJH0WiHf5xOkYHUe/4T/fIiidEvr6VxT9fG2dnUi8ZhwOCoBwciXhZVLPGo3JZxX5YF67MmJ4Br4S0iQBeWQXz0S1gxk2BcHTp8P+QusAlOesf5S4Gyais8UHbR9i8f7wpzFk1qhgclYBgPSNBnWdiUkXuilqZt7SYe8P1lTIhn7qdBiAsmbOJ+p+S3r9Fu++VeGOkv+Qk7N5RdM12VI9OKSuCzZa7fKiqDizCyePYP/C7rPU47yiqX/OY8fl/mHGGIYL822zgmegcRBDtI8qzGRZpeBymWkxNbKyPCunc0ek6nxmgi58bS4+s66dR7xbcLEr5Kq7u0f5j0NuKSYYlMMIOWAXYCBRKWwZaYMT40Uu9OzONB13aXxddHpRSxdthyKG074tzyjJP6TZVMoA8tL5KeSeHRevXoVTWrUSm6mSnVBvr9vf08jeEe+gz5HlJW9cUUUd/6s94HMxfaVrZVi3XqtJYp64/jRa2Vs82/i2B1rFTd4FePQuLeAUvQaNSlhsv0sUE6wUJ656jDVPmgvw6DfIIO5vnfG3U2U7XC3/g+lt3GXs/E/aeCc5Du0fzB/1RLEXoyKQ5yTVjheH3lmFk5lFpGAqP+6pht6cw0hcp8Fd6ZJeSn0buuMvyEBNfDQmeBrGx8RsJmcoHG9DYnbnjhUhTQQyZy2zU=
  - secure: ZCQYoYTyq31SDhvYK3YyApt2Y6Csarbz3qAppOYcXzXdO3zq3JNewdZhxd67KMZNj5OEEfb5vgDYZNGP3dpjHpsBY0RfQOGtWTK3BcJzrf8LXWPz4rU6ttheOY7Zn78bJwrYxE8PTDIuckeHlUE/nQ9XdnwvEF1wYEg2ubKUzq2oB+A4DnAAZcDV1jsovctJLTwDkDY7o6PemxXBn4p4DSuU3RyIn7KTwZ0Hoc5q0ZxH2qABBOx0oKabycE6YnjdXuVmxsLyoui15j59iASYT00wCsw+HFNoicpsnh7SSC6kNngSr6x31WvOUMQ/tn2PhrvCX+YUdYUPuV/OS0XnoQefow47Vq5is3O+pl+M5i3Czwg9ePzrWPVcawjc3y6FZBQ47s9KU3VAp8v80yRkNnJoMtyLgtJYhZU5Is3PvHZYnounKTqtZl2KVFtHZyqXsKQByOyVfZxkArTFJE53HGp5uIqXRICorsaJbPe+jpNpvb217NpBqS1aBR9OhVGqL2eA9fNBTyVhMhCTw4NP2Zsu8MsBKded+HqIqh/8gFv8lu9JV6rjPmnP8Qq8UjJvTxSpegUR0QozmycKg1jQw3wkDE1hOctWX9FRC9oqHZziWzxGtYle48e0OFbZkk6v6dVUaGYLIU2VtApQRfQqAxUIdc2HWX+i51Rs9MYVWjo=
